remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//cyberixae.github.io/experimental-ts/"
  "API Reference":
    - "//cyberixae.github.io/experimental-ts/modules/"
  "GitHub":
    - "//github.com/cyberixae/experimental-ts"
